name: Awesome Lint

on:
  push:
    branches:
      - main
    paths:
      - "readme.md"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch full history to allow repo age check

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Run awesome-lint
        run: npx awesome-lint
